SHOW DATABASES;
USE NIT
SHOW TABLES;
CREATE TABLE EMP(ID INT not NULL primary KEY, SALARY INT , EMPCODE INT ,NAME VARCHAR(30));
SHOW TABLES;
INSERT INTO EMP VALUES(1, 25000, 1, 'ADARSH'),(2, 28000, 2, 'ROHAN'),(3, 32000, 3, 'PRIYA'),(4, 24000, 4, 'SNEHA'),(5, 30000, 5, 'VIKRAM');
SELECT * FROM EMP;
SELECT * FROM STUDENT INNER JOIN EMP ON STUDENT.ID=EMP.ID;
SELECT * FROM STUDENT LEFT JOIN EMP ON STUDENT.ID=EMP.ID;
